# Generated by Django 5.1.6 on 2025-02-25 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_question_type_matchpair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='assessment',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='feedback',
            field=models.CharField(choices=[('deferred', 'Deferred Feedback'), ('immediate_question', 'Immediate per Question'), ('immediate_section', 'Immediate per Section'), ('none', 'No Feedback')], default='deferred', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='grading_method',
            field=models.CharField(choices=[('auto', 'Self-Corrected'), ('manual', 'Manual'), ('partial', 'Partially Corrected')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assessments/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='layout',
            field=models.CharField(choices=[('all_one_page', 'All questions on one page'), ('each_question', 'Each question on a separate page'), ('all_sections', 'All sections on one page'), ('each_section', 'Each section on a separate page')], default='all_one_page', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='navigation',
            field=models.CharField(choices=[('free', 'Free'), ('sequential', 'Sequential')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='assessment',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='unanswered_prompt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points for this question'),
        ),
    ]
